{% set name = "python-decouple" %}
{% set version = "3.3" %}
{% set sha256 = "55c546b85b0c47a15a47a4312d451a437f7344a9be3e001660bccd93b637de95" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - decouple

about:
  home: https://github.com/henriquebastos/python-decouple/
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Strict separation of config from code.
  description: |
    Decouple helps you to organize your settings so that you can change 
    parameters without having to redeploy your app.
  doc_url: https://github.com/henriquebastos/python-decouple/
  dev_url: https://github.com/henriquebastos/python-decouple/

extra:
  recipe-maintainers:
    - xmnlab
